# Generated by Django 2.0.4 on 2020-03-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0021_remove_mechanic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='phone',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='timetable_number',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='month',
            name='days_in_month',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='month',
            name='working_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
