# Generated by Django 2.0.4 on 2020-03-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0022_auto_20200329_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='phone',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='timetable_number',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
